### ISSUE TITLE
proxy_Url 使用了两个ip，team账号总是被封

### ISSUE THREAD

**Issue by tomridder** [lanqian528/chat2api#100]
proxy_Url 使用了两个美国 代理 ip
tokens 使用了 三个 plus账号，用team弄的
在这个条件下 team账号使用了 不到一天时间总是被封
应该怎么规避 
------------------
准备用加拿大的一个ip试试

**Comment by lanqian528** [comment]
team封号不是很正常么，是正规渠道充值么

**Comment by tomridder** [comment]
是正规的，美国本地的信用卡
那准备用多个plus 账号 分开 和一个代理ip试试看

**Comment by tomridder** [comment]
都解决了 原来是要更新docker images
