### ISSUE TITLE
日志不显示具体使用了哪个token

### ISSUE THREAD

**Issue by criswu99** [lanqian528/chat2api#105]
使用chat2api自带的token管理，上传多个token后，使用AUTHORIZATION进行多账号轮询，没办法判断是哪个token报错。希望能在日志中加个使用token的序号，或者token的前几个字符。
![图片](https://github.com/lanqian528/chat2api/assets/160563239/2d3e7d97-d68d-4367-ae8d-d63651195b9c)

**Comment by zexry619** [comment]
How to activate this debugging mode?

**Comment by lanqian528** [comment]
v1.3.4 已支持
