### ISSUE TITLE
Openai-Sentinel-Turnstile-Token Generation

### ISSUE THREAD

**Issue by zfcsoftware** [lanqian528/chat2api#106]
Hello, it is currently integrated but not checked. It will probably be mandatory soon and the library will not work. Is this issue in your attention, are you considering integration?

![image](https://github.com/lanqian528/chat2api/assets/123484092/093597bb-d3f3-495e-b7e1-d4205409d70c)
![image](https://github.com/lanqian528/chat2api/assets/123484092/57eb554b-386e-4255-a3b9-36897d59db69)

**Comment by lanqian528** [comment]
我不知道这个算法是什么，也没有时间去研究，需要等待社区其他开发者

**Comment by zfcsoftware** [comment]
> 我不知道这个算法是什么，也没有时间去研究，需要等待社区其他开发者

I'm interested in this topic, I'm looking into it too. It's only been discussed on linux.do, but it's not solved there either. When I find some information I will add it here, thank you.

**Comment by lanqian528** [comment]
> > 我不知道这个算法是什么，也没有时间去研究，需要等待社区其他开发者
> 
> 大佬已经研究出来了 [xqdoo00o/ChatGPT-to-API#69](https://github.com/xqdoo00o/ChatGPT-to-API/issues/69)

多谢提醒，有空会添加
