### ISSUE TITLE
401 

### ISSUE THREAD

**Issue by MaZhaolin** [LanQian528/chat2api#11]
AUTHORIZATION的token是指access token吗 我填或者不填都是401 ，请教一下该怎么配置，代理我确认了没问题

**Comment by MaZhaolin** [comment]
> 不需要填AUTHORIZATION，401可能代理的地区不支持
<img width="399" alt="image" src="https://github.com/LanQian528/chat2api/assets/13713662/7188f1ae-1ff1-4d87-8245-77b885cb0685">
<img width="946" alt="image" src="https://github.com/LanQian528/chat2api/assets/13713662/16c6c5f1-82a1-4e10-8e7e-33acdf0aab29">

这样配置可以吗
这个支持哪些地区 我切了日本美国的节点都不行

**Comment by MaZhaolin** [comment]
<img width="1041" alt="image" src="https://github.com/LanQian528/chat2api/assets/13713662/b0a316c3-80fc-4215-ac42-28a7a1ebc6a7">
又遇到了新的问题，是GPT检测到了吗

**Comment by LanQian528** [comment]
用最新版
