### ISSUE TITLE
3.5 免登录报错 Unusual activity has been detected from your device. Try again later.

### ISSUE THREAD

**Issue by tomridder** [lanqian528/chat2api#115]
guichaoran@guichaorandeMacBook-Pro ~ % curl --request POST \
  --url http://154.40.47.16:5005/v1/chat/completions \
  --header 'content-type: application/json' \
  --data '{
    "model": "gpt-3.5-turbo",
    "messages": [
        {
            "role": "user",
            "content": "https://tomchat.shop/uploads/1715246029371.pdf 这是什么 "
        }
    ]
}'
{"detail":"Unusual activity has been detected from your device. Try again later. (89bd7c34ab2508de-LAX)"}%

**Comment by lanqian528** [comment]
ip不支持免登
