### ISSUE TITLE
使用 zeabur 部署完，打开5005端口webui正常显示，但是一直显示需要机器人认证，绕不过去

### ISSUE THREAD

**Issue by Gijela** [lanqian528/chat2api#119]
如题，
<img width="1306" alt="image" src="https://github.com/lanqian528/chat2api/assets/82071209/83368db9-acaa-466f-8103-e8cfd0c4dedb">

日志信息有很多403，请问这种怎么解决呢？

**Comment by Gijela** [comment]
日志信息有很多403，请问这种怎么解决呢？
<img width="1361" alt="image" src="https://github.com/lanqian528/chat2api/assets/82071209/03f29a93-7e93-40de-811d-e4128a8b77be">

**Comment by CliffHan** [comment]
虽然我不是用 zeabur 部署的，但遇到同样问题

**Comment by QAbot-zh** [comment]
ui 用不了就晾着吧，这个项目主要是用来转 api 的

![image](https://github.com/lanqian528/chat2api/assets/40236765/a720eea4-2c6a-4e11-8fab-a06cc14d140f)

**Comment by CliffHan** [comment]
> ui 用不了就晾着吧，这个项目主要是用来转 api 的
> 
我理解这个项目是不是模拟 web 访问转换成 api 的？
如果 web 代理访问不上去，那么 api 是否正常？

**Comment by QAbot-zh** [comment]
> > ui 用不了就晾着吧，这个项目主要是用来转 api 的
> 
> 我理解这个项目是不是模拟 web 访问转换成 api 的？ 如果 web 代理访问不上去，那么 api 是否正常？

不太影响，我web能访问，但是提问会报错，api 能正常使用

**Comment by lanqian528** [comment]
换ip
