### ISSUE TITLE
突然 报错 Our systems have detected unusual activity coming from your system. Please try again later.

### ISSUE THREAD

**Issue by tomridder** [lanqian528/chat2api#130]
chat2api           | 2024-08-06 19:08:02,248 | ERROR | --------------------------------------------------
chat2api           | | Error: Our systems have detected unusual activity coming from your system. Please try again later.
chat2api           | └-----------------------

求问什么导致的

**Comment by tomridder** [comment]
是次数太多导致的吗

**Comment by lanqian528** [comment]
ip不干净

**Comment by tomridder** [comment]
刚开始的时候这个ip 是OK的 。如果用多个proxy.容易导致账号被封 。没办法

**Comment by tomridder** [comment]
> ip不干净

如果想买干净的ip 应该在哪个网址买哪个国家的ip呢

**Comment by tomridder** [comment]
> 如果用多个proxy.容易导致账号被封


> 感觉是有什么特征被识别了，用了全新比较干净的ip，一开始可以请求，多次后就变成了Our systems have detected unusual activity coming from your system.

是的 ，如果买多个ip还害怕账号被封，一个ip 又容易出现异常

**Comment by lanqian528** [comment]
换多个ip

**Comment by zhuiyue132** [comment]
> chat2api | 2024-08-06 19:08:02,248 | ERROR | -------------------------------------------------- chat2api | | Error: Our systems have detected unusual activity coming from your system. Please try again later. chat2api | └-----------------------
> 
> 求问什么导致的

好像是因为有 system role 的提示词。我也遇到了。去除 system role 后可以正常返回。

**Comment by Oiuxxbei** [comment]
好像是频繁切换IP造成的，后来我清理缓存就正常了
