### ISSUE TITLE
换成动态代理以后报下面的错误

### ISSUE THREAD

**Issue by tomridder** [lanqian528/chat2api#132]
funcaptcha_solver  | 2024-08-07 17:10:54,914 | ERROR | ------------------------------------------------------------------------------------------------------------------------
funcaptcha_solver  | | {'msg': 'Failed: 3d_rollball_objects, 风控的游戏类型', 'variant': None, 'solved': False, 'token': '12517e9673f494b97.0071093702|r=us-west-2|meta=3|metabgclr=transparent|metaiconclr=%23757575|guitextcolor=%23000000|pk=35536E1E-65B4-4D96-9D97-6ADB7EFF8147|at=40|rid=77|ag=101|cdn_url=https%3A%2F%2Ftcr9i.chat.openai.com%2Fcdn%2Ffc|lurl=https%3A%2F%2Faudio-us-west-2.arkoselabs.com|surl=https%3A%2F%2Ftcr9i.chat.openai.com|smurl=https%3A%2F%2Ftcr9i.chat.openai.com%2Fcdn%2Ffc%2Fassets%2Fstyle-manager', 'waves': None, 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.0.0', 'proxy': None}
funcaptcha_solver  | └--------------------------------------------------------------------------------------------------------

**Comment by lanqian528** [comment]
你的动态代理不干净，出码了
