### ISSUE TITLE
访问模型gpt-4o,gpt-4回答的内容与ChatGPT官方不一致，问图片表格类提示不支持，官网使用是支持的。

### ISSUE THREAD

**Issue by zaohuayudie** [lanqian528/chat2api#133]
部署服务器后，使用模型gpt-4o，有传入access_token进行测试

model: gpt-4o
message:  "give me a cat image."

结果：
ChatGPT官网会给出图片
chat2api提示不支持图片

请问是什么原因？

**Comment by lanqian528** [comment]
你这换ip吧，降智了
