### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by 2693551060** [lanqian528/chat2api#134]
大佬什么时候考虑支持普号的dall-e-3

**Comment by lanqian528** [comment]
一直都支持啊

**Comment by lanqian528** [comment]
聊天的时候让他画图就行

**Comment by 2693551060** [comment]
怎么触发（或者说怎么让他精准调用dall-e-3，就成功了一次），普号有时候能画，有时候不能画（有200+的号，应该不是到上限了）

![失败案例](https://image.chenjianming.fun/file/688c87cd727b63e6ee0f3.png)
