### ISSUE TITLE
API能否用Python OpenAI的库

### ISSUE THREAD

**Issue by Animaxx** [lanqian528/chat2api#140]
能否直接用OpenAI的方式调用chat2api?

**Comment by BlueSkyXN** [comment]
？你这个问题和问比亚迪的电动汽车是不是机动车是一样的

**Comment by Animaxx** [comment]
似乎如果我openai来调用就返回403 PermissionDeniedError: Error code: 403 - {'detail': 'Ark0se service required'}，但是

curl --location 'http://127.0.0.1:5005/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer [key]' \
--data '{
     "model": "gpt-4o",
     "messages": [{"role": "user", "content": "Say Hello!"}],
     "stream": true
   }'

这样可以

**Comment by Animaxx** [comment]
我就这么用也没什么特殊

from openai import OpenAI

client = OpenAI(
    base_url="http://127.0.0.1:5005/v1",
    api_key=access_token
)
response = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {"role": "user", "content": "Hi!"}
    ],
    # stream=True
    stream=False
)
print(response.choices[0].message.content)

**Comment by lanqian528** [comment]
这个跟你使用什么格式没关系，只是你没配置ark0se

**Comment by Animaxx** [comment]
有什么文档说明一下 ark0se么 https://www.ark0selabs.com/ 似乎访问不了?

**Comment by lanqian528** [comment]
https://github.com/lanqian528/chat2api/blob/main/docker-compose.yml
