### ISSUE TITLE
system role 貌似失效了

### ISSUE THREAD

**Issue by zhuiyue132** [lanqian528/chat2api#141]
添加了 system role 后 报错Unusual activity has been detected from your device. Try again later.
![image](https://github.com/user-attachments/assets/20ddb1c5-47b5-437e-b766-04082104b769)

使用同一个 access_token, 去除system role 后
![image](https://github.com/user-attachments/assets/953cc9dd-145c-4e65-b41f-d99281ab2e43)

这中间只删除了 system role，稳定复现。

**Comment by zhuiyue132** [comment]
![image](https://github.com/user-attachments/assets/21fbcf36-f713-47dd-b0db-914f5d0c3cd3)
这是这两次请求的对应的日志。

**Comment by lanqian528** [comment]
你是不是用了new.oaifree.com，这个站做了限制，请用demo.oaifree.com

**Comment by zhuiyue132** [comment]
感谢回复。确实如此。在 2024年9月13日，12:09，LanQian ***@***.***> 写道：﻿
你是不是用了new.oaifree.com，这个站做了限制，请用demo.oaifree.com
