### ISSUE TITLE
访问会间隔失败,成功访问后一次必定401

### ISSUE THREAD

**Issue by kaipol** [LanQian528/chat2api#145]
![image](https://github.com/user-attachments/assets/9890ab76-a34a-4135-b952-f340d5208a10)
![image](https://github.com/user-attachments/assets/f6a4ac35-e5cb-49b6-ad0b-5329d6e99902)

如图,在401报错失败后立刻重试会成功,立刻重试后又报401失败; 间隔一段时间尝试仍是成功后401报错后成功

**Comment by lanqian528** [comment]
看起来是accesstoken失效了

**Comment by kaipol** [comment]
> 看起来是accesstoken失效了

是指一部分失效了吗，我是成功-失败-成功-失败间隔出现的
