### ISSUE TITLE
建议：能否为token绑定映射值

### ISSUE THREAD

**Issue by RANSAA** [LanQian528/chat2api#146]
如题能否为AccessToken提供映射名，即添加tokens时对应的每一个token绑定一个名称，请求时直接传输这个映射值；
然后服务端通过这个映射值找到对应真实的token，并且更新token时更新映射值对应的真实AccessToken等信息即可；
这样就可以减轻请求时频繁更新APIKEY的值。

**Comment by lanqian528** [comment]
这不就是refresh_token么
