### ISSUE TITLE
一个关于token管理的建议

### ISSUE THREAD

**Issue by kkbaitu6** [LanQian528/chat2api#157]
1：新增token时，可以写备注，方便记录是哪个号(不写也可以)；
2：新增一个token管理后台界面，然后有个批量测试或者单点测试，随时可以查看token是否失效，因为openai偶尔会封号。
3：随便一说，希望采纳！！！！！！
4：感谢作者大大

**Comment by lanqian528** [comment]
建议用one-api管理token哈
