### ISSUE TITLE
能否access token和api key混用

### ISSUE THREAD

**Issue by TelBotDev** [LanQian528/chat2api#158]
chat2api 的 access token 和 OpenAI 账户页面申请的 api key 能混用吗？最近发现使用nextchat + chat2api 频繁时会被限制，但我又不想再开一个 Plus 账号。正好手上还有一些 api key 的额度，想着能不能把它加进去做个负载均衡。然而，尝试后发现是不允许的，系统会将 api key 当作 access token 处理，并返回报错。

**Comment by lanqian528** [comment]
用one-api
