### ISSUE TITLE
load_dotenv()   change to load_dotenv(encoding='ascii') in config.py

### ISSUE THREAD

**Issue by yuanzhanghu** [LanQian528/chat2api#16]
since we might copy a invalid access token from firefox (string was truncated and a unicode character '...' is added inside the string) . 

adding encoding='ascii' in load_dotenv() can add more check on a valid access token, which avoid weird issue to debug. 

Thanks for your project.

**Comment by LanQian528** [comment]
Thank you for your suggestion. It will be added my in next commit.
