### ISSUE TITLE
请问 README 中的这个 https://www.ark0selabs.com/ 链接是作者本人的吗？

### ISSUE THREAD

**Issue by k0baya** [LanQian528/chat2api#162]
目前该域名已经被 `301` 重定向到一个号商发卡网，如果不是作者本人提供的，望删掉这个地址，避免对用户造成误导。
![image](https://github.com/user-attachments/assets/5210765a-be05-432f-b691-ddf79555eca4)

**Comment by lanqian528** [comment]
不是，我瞎编的域名被别人买下来了😄

**Comment by k0baya** [comment]
> 不是，我瞎编的域名被别人买下来了😄

```
https://chatgpt.aicnm.cc/login
```
那么这个网址是作者本人提供的吗？请问可以直接填入`CHATGPT_BASE_URL`使用吗，是不是可以不降智😋
