### ISSUE TITLE
Still trying to connect to proxy even PROXY_URL is []

### ISSUE THREAD

**Issue by yuanzhanghu** [LanQian528/chat2api#17]
funcaptcha_solver  | http://127.0.0.1:5006/token                                                                                                                                       
funcaptcha_solver  |  * Serving Flask app 'app'                                                                                                                                        
funcaptcha_solver  |  * Debug mode: off                                                                                                                                                
funcaptcha_solver  | 2024-04-21 21:28:00,322 | INFO | WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.           
funcaptcha_solver  |  * Running on all addresses (0.0.0.0)                                                                                                                             
funcaptcha_solver  |  * Running on http://127.0.0.1:5006                                                                                                                               
funcaptcha_solver  |  * Running on http://172.18.0.3:5006                                                                                                                              
funcaptcha_solver  | 2024-04-21 21:28:00,322 | INFO | Press CTRL+C to quit                                                                                                             
chat2api           | 2024-04-21 21:28:00,506 | INFO | Environment variables (no AUTHORIZATION):                                                                                        chat2api           | 2024-04-21 21:28:00,507 | INFO | CHATGPT_BASE_URL:      ['https://chat.openai.com']                                                                               
chat2api           | 2024-04-21 21:28:00,507 | INFO | ARKOSE_TOKEN_URL:      ['http://arkose:5006/token']                                                                              
chat2api           | 2024-04-21 21:28:00,507 | INFO | PROXY_URL:             []                                                                                                        chat2api           | 2024-04-21 21:28:00,507 | INFO | HISTORY_DISABLED:      True                                                                                                      chat2api           | 2024-04-21 21:28:00,507 | INFO | RETRY_TIMES:           3                                                                                                         
chat2api           | 2024-04-21 21:28:00,557 | INFO | Started server process [1]                                                                                                       
chat2api           | 2024-04-21 21:28:00,558 | INFO | Waiting for application startup.                                                                                                 
chat2api           | 2024-04-21 21:28:00,558 | INFO | Application startup complete.                                                                                                    
chat2api           | 2024-04-21 21:28:00,558 | INFO | Uvicorn running on http://0.0.0.0:5005 (Press CTRL+C to quit)                                                                    
chat2api           | 2024-04-21 21:28:08,541 | INFO | 172.18.0.1:55804: POST /v1/chat/completions HTTP/1.1 500 Internal Server Error                                                   
chat2api           | 2024-04-21 21:28:08,543 | ERROR | Exception in ASGI application                                                                                                   
chat2api           | Traceback (most recent call last):                                                                                                                                
chat2api           |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 779, in urlopen                                                                  
chat2api           |     self._prepare_proxy(conn)                                                                                                                                     
chat2api           |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1048, in _prepare_proxy                                                          
chat2api           |     conn.connect()                                                                                                                                                
chat2api           |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 633, in connect                                                                      
chat2api           |     self._tunnel()  # type: ignore[attr-defined]                                                                                                                  
chat2api           |     ^^^^^^^^^^^^^^
chat2api           |   File "/usr/local/lib/python3.11/http/client.py", line 943, in _tunnel
chat2api           |     raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
chat2api           | OSError: Tunnel connection failed: 403 Access denied
chat2api           | 
chat2api           | The above exception was the direct cause of the following exception:
chat2api           | 
chat2api           | urllib3.exceptions.ProxyError: ('Unable to connect to proxy', OSError('Tunnel connection failed: 403 Access denied'))

**Comment by netptop** [comment]
This is weird, the issue disappeared.
