### ISSUE TITLE
報錯{ "detail": "Gateway is disabled" }

### ISSUE THREAD

**Issue by GaryZong** [LanQian528/chat2api#173]
我使用Docker拉取latest之後部屬後的網頁報錯{ "detail": "Gateway is disabled" }
防火牆以及防毒關閉測試也是一樣報錯
![image](https://github.com/user-attachments/assets/28580c4f-1673-46b0-a3fa-fc616e877412)
![image](https://github.com/user-attachments/assets/527ee230-206f-40e3-ab3d-65ea85536d29)

**Comment by OraCatQAQ** [comment]
没开Gateway所以没有登陆界面，设置环境变量ENABLE_GATEWAY为true，或者直接访问localhost:5005/tokens输入accessToken来使用 @GaryZong

**Comment by GaryZong** [comment]
OK謝謝以解決了
