### ISSUE TITLE
Python OpenAI库的openai.ChatCompletion.create方法可以指定使用Team版的工作区吗？

### ISSUE THREAD

**Issue by ChthoIly** [LanQian528/chat2api#181]
我在用Python的OpenAI库来发送API请求，但是我实在是找不到怎么把Team的ChatGPT-Account-ID传进去。我可以正常传AT来对话，可以正常使用个人版的对话额度。我怎么用Python的OpenAI库写带ChatGPT-Account-ID的请求啊？

**Comment by lanqian528** [comment]
AccessToken,ChatGPTAccountID

这样作为一整行输入，英文逗号分割

**Comment by ChthoIly** [comment]
感谢。

是我钻牛角尖了，我头铁一直在想怎么传Authorization: Bearer Header。没想到可以直接当apikey传。。。
