### ISSUE TITLE
上传token报错

### ISSUE THREAD

**Issue by ruili0523** [LanQian528/chat2api#184]
![image](https://github.com/user-attachments/assets/2182e085-c24a-468a-b0f9-d599110366cd)

![image](https://github.com/user-attachments/assets/0568fd68-f5b2-4fdc-a0a3-ff9f656deb2e)

![image](https://github.com/user-attachments/assets/c97d6978-f73e-4750-b20f-a5f449b1f71e)

这儿读取token文件的目录路径好像不对，在容器/app/data下会报错，放到容器/data下运行正常

**Comment by gua12345** [comment]
我在用容器部署前用源码在win上测试了，去掉../就行了

**Comment by lanqian528** [comment]
之前dev版修了，main版一直忘记修了，刚刚推了main版的，更新一下版本就行
