### ISSUE TITLE
左侧部分不显示且不能用

### ISSUE THREAD

**Issue by docker-master** [LanQian528/chat2api#186]
![image](https://github.com/user-attachments/assets/c46cd125-dfe1-4ae1-8122-d40e914007f6)
如图，全局美国代理

**Comment by lanqian528** [comment]
无法连接到chatgpt，或账号错误

**Comment by qixinwuchen** [comment]
这个最终是怎么解决的，我通过docker方式部署在华为云的服务器上，也遇到了同样的问题
@lanqian528 难道云服务器必须要能连接到chatgpt吗，上面没有梯子
