### ISSUE TITLE
代理 URL 如何设置

### ISSUE THREAD

**Issue by TomBener** [LanQian528/chat2api#20]
你好，我遇到了 `400` 的问题，请问应该如何设置 `PROXY_URL=your_first_proxy, your_second_proxy`？这里的 `your_first_proxy` 应该填什么？谢谢！

**Comment by LanQian528** [comment]
填http代理URL，格式为：http://ip:port，如果代理需要用户验证，格式为http://username:password@ip:port

**Comment by TomBener** [comment]
好的，谢谢。不过请问怎么才能获得一个 `http://ip:port` 呢？

**Comment by LanQian528** [comment]
这个不做解答
