### ISSUE TITLE
TURNSTILE_SOLVER_URL 问题

### ISSUE THREAD

**Issue by leadscloud** [LanQian528/chat2api#202]
新版本中去掉了生成`process_turnstile_token` 使用 TURNSTILE_SOLVER_URL代替，但没看到解释说明

如果使用chatgpt.com最新的payload data，会出现 

`Our systems have detected unusual activity coming from your system. Please try again later. `

**Comment by lanqian528** [comment]
turnstile算法无法公开，出现`Our systems have detected unusual activity coming from your system. Please try again later. `很有可能是因为你的ip有问题无法免登，建议使用账号请求
