### ISSUE TITLE
页面故障

### ISSUE THREAD

**Issue by yangyunwei123** [LanQian528/chat2api#204]
大佬救命
部署完就成这样了
![IMG_2697](https://github.com/user-attachments/assets/c3d29938-eadd-4ebd-8ff7-9e06306c8e1e)
服务器是新加坡华为云
变量有两个
- AUTO_SEED=false
- ENABLE_GATEWAY=true

**Comment by lanqian528** [comment]
AUTO_SEED=true试试

**Comment by yangyunwei123** [comment]
> AUTO_SEED=true试试

已成功，谢谢🙏大佬
