### ISSUE TITLE
想问一下有人用chat2api会导致账号被精准锁定降智吗？

### ISSUE THREAD

**Issue by ChthoIly** [LanQian528/chat2api#205]
最近用了一阵子的chat2api大概一个月左右吧。单个个人Team账号，用量不是很大肯定没有触发到对话上限。前几天官网Web版所有模型除了纯文本对话其他功能全部都用不了了。读不了图片文件也不出图了问GPT就说目前没有能力读取文件。感觉是被精准锁定降智了。试了其他设备网络登录都不行，但是同一个设备网络换一个其他的号就能正常用。

之后给官方发了邮件，官方也没正面回答就让刷新和重置浏览器。官方也没说我违规，也没收到警告邮件。收到官方邮件回复的当天就又好了。不知道是不是用chat2api被算法发现了。

**Comment by QAbot-zh** [comment]
很多没用过 chat2api 的也被锁号降智了，谁也不知道 OpenAI 的降智政策

**Comment by chenjingwei0103** [comment]
我刚刚测试了下，同一个ip ，两个号用官网的都可以画图，然后有一个用chat2api前5分钟都可以画图，之后就降智了，切回官网的也是降智的，应该是对账号的锁定，没用过chat2api还是可以正常画图

**Comment by CodingXiaoheng2** [comment]
我的一个普号也是这样，用chat2api一段时间后就降智了，切回官网的也是降智的。用量甚至就五六条对话的样子。

**Comment by ChthoIly** [comment]
那和chat2api没啥关系？正常用也会锁号降智？
我以为钻空子被算法发现了

**Comment by lanqian528** [comment]
使用chat2api官网想识别是能识别出来的，所以觉得有问题就不要用了

**Comment by mcdullmedia** [comment]
我昨天也試過了, 警告是有其他人在使用我的戶口, 所以停止了部份功能.
停了chat2api過一天就正常了.
