### ISSUE TITLE
[Bug] team 团队被停用的情况下仍然返回订阅类型为 team

### ISSUE THREAD

**Issue by lvguanjun** [LanQian528/chat2api#210]
![image](https://github.com/user-attachments/assets/e4f5326b-75b0-431d-8aae-0a3a11067910)

如图，当 check 账号信息时，如果账户存在一个被 ban 的 team 中，该账号订阅类型预期是号主的订阅类型而不是 team 。

位置： gateway/share.py/chatgpt_account_check: 157

**Comment by lanqian528** [comment]
自行退出team就行吧

**Comment by lvguanjun** [comment]
这倒没有细想，只是从 API 的角度来看，提供的信息是不正确的

**Comment by lanqian528** [comment]
可以试试最新版，我尝试修复了，但是我没有这样的team，没测试
