### ISSUE TITLE
ip:port正常，hostname:port 丢失port，无法访问

### ISSUE THREAD

**Issue by tyouzu1** [LanQian528/chat2api#214]
![image](https://github.com/user-attachments/assets/6adb9424-75c3-4d6f-851f-19afb55d66bf)

![image](https://github.com/user-attachments/assets/7cab5c85-fb46-4946-ba24-1843dd1fbc14)

域名访问，端口不见了，ip访问，端口还在
家宽，只能带端口，请问这个有办法吗，现在只能自己再代理一层去转发到指定端口

**Comment by lanqian528** [comment]
再代理一层吧
