### ISSUE TITLE
请问这里gpt-3.5-turbo如何免登陆使用？

### ISSUE THREAD

**Issue by Davidasx** [LanQian528/chat2api#217]
直接运行了`python app.py`，模型gpt-3.5-turbo，没有传入token，请问为什么用不了了？
另外，自己，抓了AccessToken后问了一下，发现用的还是4o系列模型，而不是3.5。
我的目的是完成非常简单的低级任务，次数要求比较多，不需要4o，所以请问还能用到3.5吗？

**Comment by lanqian528** [comment]
官方早就不支持gpt3.5了
