### ISSUE TITLE
并发上来了内存泄漏非常严重

### ISSUE THREAD

**Issue by bfgngfnfgmnggn** [LanQian528/chat2api#23]
直到占满20多g的内存死机
HISTORY_DISABLED已经设置false

**Comment by LanQian528** [comment]
多少qps呢，我这边没有复现

**Comment by Ranglage** [comment]
老版本的fastapi确实有内存泄漏问题，你更新一下fastapi版本？

**Comment by LanQian528** [comment]
已经定位到问题，并在最新版修复 #783168dbe1e3a4d8b14db7633fe3ff219cb4dc93
