### ISSUE TITLE
关于   AUTHORIZATION  

### ISSUE THREAD

**Issue by Dooy** [LanQian528/chat2api#28]
填写了 AUTHORIZATION 一直都是 {"detail":"Unauthorized"}

不管是用45位的 `refresh_token`
还是用 `eyJhbGciOi` 开头的 `accessToken` 都是报  {"detail":"Unauthorized"}

**Comment by Dooy** [comment]
用Docker 搭建的
<img width="701" alt="image" src="https://github.com/LanQian528/chat2api/assets/3765401/0c631c54-2bc5-444e-a9ee-6493220fe2e8">

**Comment by Dooy** [comment]
用 refresh_token 也不行
<img width="327" alt="image" src="https://github.com/LanQian528/chat2api/assets/3765401/c1357866-1f0f-4048-9b68-5d3b675bb69b">

**Comment by Dooy** [comment]
不加 AUTHORIZATION 免登录 没问题

**Comment by LanQian528** [comment]
> 不加 AUTHORIZATION 免登录 没问题

你理解错AUTHORIZATION这个环境变量的问题了，这是自己给自己设置密码的意思

**Comment by Dooy** [comment]
gpt4 要如何传入 `AccessToken` 或 `RefreshToken`
能让给一个 curl demo?

**Comment by Dooy** [comment]
```
curl --location 'http://127.0.0.1:5005/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'AUTHORIZATION: Bear AccessToken-or-RefreshToken' \
--data '{
     "model": "gpt-4",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "stream": true
   }'
```

**Comment by LanQian528** [comment]
> ```
> curl --location 'http://127.0.0.1:5005/v1/chat/completions' \
> --header 'Content-Type: application/json' \
> --header 'Authorization: Bearer AccessToken-or-RefreshToken' \
> --data '{
>      "model": "gpt-4",
>      "messages": [{"role": "user", "content": "Say this is a test!"}],
>      "stream": true
>    }'
> ```

是的，直接这样使用就行了
