### ISSUE TITLE
关于上传非图片的如PDF等有问题

### ISSUE THREAD

**Issue by Dooy** [LanQian528/chat2api#29]
关于上传非图片的如PDF等有问题
需要check，不check 导致读取不到
<img width="566" alt="image" src="https://github.com/LanQian528/chat2api/assets/3765401/61bd8b33-567a-4350-bd23-458c2bc337bb">

<img width="892" alt="image" src="https://github.com/LanQian528/chat2api/assets/3765401/21999277-255b-4f4b-a978-a747469f286a">

```json
{
    "id": "file-CnBhx5ULQN6514xDgGeH66u9",
    "name": "dmr7brxv.pdf",
    "creation_time": "2024-05-01 15:38:39.956360+00:00",
    "state": "ready",
    "ready_time": "2024-05-01T15:38:53.435776",
    "size": 1457326,
    "metadata": {
        "retrieval": {
            "status": "success", #这个需要 success 或者 skipped
            "file_size_tokens": 34812
        }
    },
    "use_case": "my_files",
    "retrieval_index_status": "success",
    "file_size_tokens": 34812,
    "variants": null
}
```
<img width="1140" alt="image" src="https://github.com/LanQian528/chat2api/assets/3765401/64235711-0f51-443d-9542-89be12b2e68a">

**Comment by LanQian528** [comment]
应该是文件太大了吧

**Comment by LanQian528** [comment]
![image](https://github.com/LanQian528/chat2api/assets/5499636/f61f6725-7155-418e-8ee1-7e8933569d70)
测试3MB的pdf可以正常读取

**Comment by Dooy** [comment]
是的文件太比较大
文件小的时候，你基本提交过去了 就状态 success

**Comment by Dooy** [comment]
官方他自己都check
这些都是check的请求
https://chat.openai.com/backend-api/files/file-CnBhx5ULQN6514xDgGeH66u9

<img width="1134" alt="image" src="https://github.com/LanQian528/chat2api/assets/3765401/2744a870-27b7-4a07-b83a-012daac70bd4">

**Comment by Dooy** [comment]
<img width="707" alt="image" src="https://github.com/LanQian528/chat2api/assets/3765401/8e96f9c4-581c-4aae-b23b-7e806ae2a4a9">

这个文件也不大1.5M
[21年NC.pdf](https://github.com/LanQian528/chat2api/files/15182525/21.NC.pdf)
