### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by 1487879421888** [LanQian528/chat2api#3]
大佬好，反馈一个问题。就是，我用这个服务的时候，全部给我拼接起来了。如图：
![image](https://github.com/LanQian528/chat2api/assets/47622641/28a50eb6-88dd-44ac-8d2b-75115737b8f1)

**Comment by LanQian528** [comment]
处理有点问题，在看了

**Comment by LanQian528** [comment]
拉一下最新镜像
