### ISSUE TITLE
验证GPT-4o的答复，似乎不是GPT-4o，而是GPT3.5

### ISSUE THREAD

**Issue by itq5** [lanqian528/chat2api#34]
转api后，调用GPT-4o实际是3.5
![image](https://github.com/lanqian528/chat2api/assets/42521985/0ad25ace-e2af-4296-830d-6a7a679c819a)
![image](https://github.com/lanqian528/chat2api/assets/42521985/cf861bdf-7a7e-4eae-9933-a44765086a52)

**Comment by lanqian528** [comment]
你的ip不支持4o，换成日本或者新加坡ip试试

**Comment by itq5** [comment]
> 你的ip不支持4o，换成日本或者新加坡ip试试

部署[chat2api](https://github.com/lanqian528/chat2api)的服务器是吗？

**Comment by lanqian528** [comment]
> > 你的ip不支持4o，换成日本或者新加坡ip试试
> 
> 部署[chat2api](https://github.com/lanqian528/chat2api)的服务器是吗？

如果不使用代理或者网关的话就是换服务器

**Comment by itq5** [comment]
> > > 你的ip不支持4o，换成日本或者新加坡ip试试
> > 
> > 
> > 部署[chat2api](https://github.com/lanqian528/chat2api)的服务器是吗？
> 
> 如果不使用代理或者网关的话就是换服务器

如何屏蔽gpt3.5的回复，只显示gpt-4o的回复，当条数受限后不回复3.5的

**Comment by lanqian528** [comment]
> > > > 你的ip不支持4o，换成日本或者新加坡ip试试
> > > 
> > > 
> > > 部署[chat2api](https://github.com/lanqian528/chat2api)的服务器是吗？
> > 
> > 
> > 如果不使用代理或者网关的话就是换服务器
> 
> 如何屏蔽gpt3.5的回复，只显示gpt-4o的回复，当条数受限后不回复3.5的

条数受限后本来就不会回复3.5，4o变3.5是因为你的ip不支持4o
