### ISSUE TITLE
报错： ChatGPT ! Unusual activity has been detected from your device. Try again later. (8852dd628a982ee7-LAX)

### ISSUE THREAD

**Issue by pengwon** [lanqian528/chat2api#36]
在本地部署后访问网页报错：

你能帮我设计一个用于教授基础编程技能的游戏概念吗？先询问我希望使用哪种编程语言。
ChatGPT
!
Unusual activity has been detected from your device. Try again later. (8852dd628a982ee7-LAX)

**Comment by lanqian528** [comment]
说明你的ip不支持免登

**Comment by baok1592** [comment]
使用zeabur部署的，美国加州，API访问同上一样，报错Unusual activity has been detected from your device. Try again later
