### ISSUE TITLE
部署到zeabur后无法访问

### ISSUE THREAD

**Issue by pengwon** [lanqian528/chat2api#37]
点击部署到zeabur后无法访问：

https://chaty.zeabur.app:5005

**Comment by lanqian528** [comment]
怎么个无法访问

**Comment by pengwon** [comment]
部署时选的美国，部署后访问 https://chaty.zeabur.app ，显示下面这个

访问 https://chaty.zeabur.app:5005 ，没有任何响应。

**Comment by pengwon** [comment]
![Uploading image.png…]()

**Comment by pengwon** [comment]
![image](https://github.com/lanqian528/chat2api/assets/4396692/2a35e47a-af29-43fb-bf2c-721fdd37b3cd)

**Comment by lanqian528** [comment]
看不出来什么问题，应该是是你自己的问题

**Comment by samggggflynn** [comment]
same here :hand:
