### ISSUE TITLE
docker国内本地部署，使用PROXY_URL 新加坡和美国都出404,可能是什么原因呢。

### ISSUE THREAD

**Issue by haso2007** [lanqian528/chat2api#39]
Unknown request URL: POST /backend-api/sentinel/chat-requirements. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.",

**Comment by haso2007** [comment]
<div class="x-grid3-row x-grid3-row-selected" id="ext-gen15826" style="margin: 0px; padding: 0px; touch-action: none; border-width: 0px 0px 1px; border-style: dotted dotted solid; border-color: rgb(172, 172, 172) rgb(172, 172, 172) rgb(235, 240, 245); border-image: initial; cursor: default; width: 731px; background-image: none; background-color: rgb(222, 236, 252) !important; color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
code 404,

**Comment by lanqian528** [comment]
别乱改环境变量就行

**Comment by haso2007** [comment]
确实，我把CHATGPT_BASE_URL填了API代理地址，罪过。有PROXY_URL本来也不需要这个API代理。现在可以了
