### ISSUE TITLE
https://github.com/Ink-Osier/GenerateArkose 此项目的ArkoseToken 是否可用？

### ISSUE THREAD

**Issue by thinker007** [lanqian528/chat2api#40]
arkose:
    image: lanqian528/funcaptcha_solver:latest
    container_name: funcaptcha_solver
    restart: unless-stopped
    ports:
      - '5006:5006'

https://github.com/Ink-Osier/GenerateArkose

各显神通 目前哪个项目比较好用？

**Comment by lanqian528** [comment]
你发的这个应该不能用了
