### ISSUE TITLE
gpt-4o使用API可以发图吗？

### ISSUE THREAD

**Issue by wobure123** [lanqian528/chat2api#44]
非常感谢大佬的项目。   我在nextchat发图给gpt-4o，回复无法查看图片，请问是chat2api不支持图片吗？

**Comment by lanqian528** [comment]
支持，可能你的ip不支持4o就会导致回复的模型变成3.5，详情看readme的常见问题

**Comment by wobure123** [comment]
我用的是azure 日本的ip，登录官网是可以用gpt-4o的。部署项目用api对话log是这样的，
![image](https://github.com/lanqian528/chat2api/assets/49982509/7a81cbf6-b92d-4e33-9dd9-906d02d462b5)，还有一个奇怪的是我进网页5005端口，没法对话，一直机器人验证，就是因为ip不行嘛？

**Comment by lanqian528** [comment]
> 我用的是azure 日本的ip，登录官网是可以用gpt-4o的。部署项目用api对话log是这样的， ![image](https://private-user-images.githubusercontent.com/49982509/332310693-7a81cbf6-b92d-4e33-9dd9-906d02d462b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzQzMjcsIm5iZiI6MTcxNjI3NDAyNywicGF0aCI6Ii80OTk4MjUwOS8zMzIzMTA2OTMtN2E4MWNiZjYtYjkyZC00ZTMzLTlkZDktOTA2ZDAyZDQ2MmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA2NDcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxZmQ4MWMxOWViZjg4NGY2ZmMxYjc2OTkwNDVjOWIxNDM0OTAyYTRjNTYzNTAzNGE4NTkyYzRjZGJiZTY0NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ujsqhU0oI8ZovHLvDAiVLqFYfJLM5X1N4rgGzIJ2mnM)，还有一个奇怪的是我进网页5005端口，没法对话，一直机器人验证，就是因为ip不行嘛？

我只能说出问题基本上都是ip问题。。。
