### ISSUE TITLE
/tokens的管理，如果token失效会自动踢除不用于轮询吗？

### ISSUE THREAD

**Issue by walkchen9** [lanqian528/chat2api#48]
/tokens的管理，如果token失效会自动踢除不用于轮询吗？
或者有没有token失败尝试另一个token的机制

**Comment by lanqian528** [comment]
> /tokens的管理，如果token失效会自动踢除不用于轮询吗？ 或者有没有token失败尝试另一个token的机制

之后会加重试功能，失效剔除暂时不考虑，因为无法判断失效原因

**Comment by lanqian528** [comment]
fe6d29648419385925abcaa91e974b6bdef0642c 已完成token失效自动重试功能
