### ISSUE TITLE
bug反馈启动不了

### ISSUE THREAD

**Issue by 1487879421888** [LanQian528/chat2api#5]
如图，docker搭建完成，没有问题，但是启动不起来。
![image](https://github.com/LanQian528/chat2api/assets/47622641/46105b25-18f7-4093-9cbe-3dfd74c2885c)
![image](https://github.com/LanQian528/chat2api/assets/47622641/035c6016-f4db-4de7-bed9-e8294f288859)
![image](https://github.com/LanQian528/chat2api/assets/47622641/b7457dad-0839-4194-8aa9-e500585625f1)

**Comment by LanQian528** [comment]
我dockerfile忘改了，已经修复，重新拉一下镜像然后与运行
