### ISSUE TITLE
关于接口传入文件问题

### ISSUE THREAD

**Issue by weikecloud** [lanqian528/chat2api#51]
想知道如何在接口传入文件呢？目前只知道如何传入图片，如果按照图片的逻辑，ChatGPT好像无法识别文件

**Comment by lanqian528** [comment]
就是一样的逻辑

**Comment by weikecloud** [comment]
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-4-turbo",
    "messages": [
      {
        "role": "user",
        "content": [
          {
            "type": "text",
            "text": "What'\''s in this image?"
          },
          {
            "type": "image_url",
            "image_url": {
              "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg"
            }
          }
        ]
      }
    ],
    "max_tokens": 300
  }' 官方的示例，image_url好像只能是图片的链接，如果是文件的链接，ChatGPT无法识别

**Comment by lanqian528** [comment]
我做了处理，可以识别

**Comment by weikecloud** [comment]
system角色这些也是可以定义吗？

**Comment by lanqian528** [comment]
> system角色这些也是可以定义吗？

可以

**Comment by weikecloud** [comment]
刚刚文件无法识别应该是普号的问题，有时候会降智，我想再了解一下，如果需要分析多个文件，该如何处理呢？还是说在image_url里面加入？

**Comment by weikecloud** [comment]
<img width="1000" alt="image" src="https://github.com/lanqian528/chat2api/assets/36788191/85ec9971-80e0-4631-b903-2955e7727935">
有时候会这样

**Comment by Yanyutin753** [comment]
那是你的普号上传文件次数达到限制了吧

**Comment by lanqian528** [comment]
普号好像一定时间内只能上传一两次文件

**Comment by weikecloud** [comment]
> 普号好像一定时间内只能上传一两次文件

我想知道，如何识别多个文件呢？

**Comment by lanqian528** [comment]
> 一样的逻辑

说过了，跟官方传图一样
