### ISSUE TITLE
建议：对token出现错误进行处理

### ISSUE THREAD

**Issue by gkingt** [lanqian528/chat2api#54]
首先感谢大佬的无私奉献，然后提一点建议：
希望对rt出现错误进行处理，查看日志当有rt由于密码错误或者账号被封失效以后，每次轮询到该rt时都会尝试进行at获取，当设置了重试次数以后则会导致频繁请求rt更新at失败。
建议增加rt失效以后从原token.txt中删除对应rt，并且从缓存中删除对应rt以防出现上面的情况，如果想避免误删可进行对删除的token进行备份操作，保存到相应的txt中

**Comment by lanqian528** [comment]
已完成
