### ISSUE TITLE
[bug] 回复内容重复

### ISSUE THREAD

**Issue by QAbot-zh** [lanqian528/chat2api#55]
今天发现它的回复内容会重复一遍，流式和非流都有这个情况：
![Clip_2024-05-24_10-21-13](https://github.com/lanqian528/chat2api/assets/40236765/cff4976b-e66d-4f2e-ba12-8542281b5cb9)

**Comment by lanqian528** [comment]
openai动回复格式了，需要重新适配一下

**Comment by QAbot-zh** [comment]
感谢大佬

**Comment by QAbot-zh** [comment]
> openai动回复格式了，需要重新适配一下

佬能推个新的docker镜像吗，我本地构建的镜像运行后一直报空回复的错误

**Comment by lanqian528** [comment]
> > openai动回复格式了，需要重新适配一下
> 
> 佬能推个新的docker镜像吗，我本地构建的镜像运行后一直报空回复的错误

早就推了啊，你删了重拉

**Comment by QAbot-zh** [comment]
OK，本地镜像的问题也找到了，之前想用Python直接跑的时候修改了app.py的端口，改回去就好了。感谢！

**Comment by haso2007** [comment]
@QAbot-zh 请问你重复的问题解决了吗，我docker部署最新版本0.6.7后就出现了重复的问题，有解吗？
