### ISSUE TITLE
启动不了  启动就停止了

### ISSUE THREAD

**Issue by cshitian** [LanQian528/chat2api#6]
Traceback (most recent call last):
  File "/app/app.py", line 4, in <module>
    from chatgpt.ChatService import ChatService
  File "/app/chatgpt/ChatService.py", line 13, in <module>
    from utils.config import history_disabled, free35_base_url_list, proxy_url_list
  File "/app/utils/config.py", line 9, in <module>
    authorization = os.getenv('AUTHORIZATION').replace(' ', '')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by LanQian528** [comment]
加一下AUTHORIZATION环境变量就行

**Comment by LanQian528** [comment]
拉新的镜像也行

**Comment by cshitian** [comment]
是这样吗？

docker run -d \
  --name chat2api \
  -p 5005:5005 \
  -e Authorization=sk-BS6WpV0bTvlhx4PQ95C088F3451056269e0282De4cF5B5Fb \
  lanqian528/chat2api:latest

**Comment by LanQian528** [comment]
> 是这样吗？
> 
> docker run -d --name chat2api -p 5005:5005 -e Authorization=sk-BS6WpV0bTvlhx4PQ95C088F3451056269e0282De4cF5B5Fb lanqian528/chat2api:latest

现在可以直接启动，使用最新镜像
