### ISSUE TITLE
网关有授权密钥，是否能够支持？

### ISSUE THREAD

**Issue by suidu-pro** [lanqian528/chat2api#61]
# 接入网关地址
      CHATPROXY: "https://demo.xyhelper.cn"
      # 接入网关的authkey
      AUTHKEY: "xyhelper"
      
      这种形式的

**Comment by lanqian528** [comment]
应该不需要写authkey，有接入点网关地址就行，使用xy付费网关记得开启环境变量的CONVERSATION_ONLY，可以减少算力消耗速度

**Comment by suidu-pro** [comment]
![image](https://github.com/lanqian528/chat2api/assets/58975755/85f6c395-71d8-4765-8663-a86c5ad7a85b)

现在自建网关，密钥是必填项，否则就是未授权状态，如果可以希望您能够支持

**Comment by lanqian528** [comment]
> ![image](https://private-user-images.githubusercontent.com/58975755/333989225-85f6c395-71d8-4765-8663-a86c5ad7a85b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3OTE3NTAsIm5iZiI6MTcxNjc5MTQ1MCwicGF0aCI6Ii81ODk3NTc1NS8zMzM5ODkyMjUtODVmNmMzOTUtNzFkOC00NzY1LTg2NjMtYTg2YzVhZDdhODViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA2MzA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzYTQ0ZTM3YmM0NzcxZDVjZTNlZTg2Yzk2YjMzODliODFjNzA0MDE5OWMxYWNjOGIyZDZmNTY2OTA2YmIzNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YAVXNUIT0c77eXsFRLogyH3EoeolD2TRyexDaHuqiTw)
> 
> 现在自建网关，密钥是必填项，否则就是未授权状态，如果可以希望您能够支持

那你要告诉我传密钥的格式啊，或者你用nginx反代的时候加一下密钥

**Comment by suidu-pro** [comment]
就是按照xy的格式，放在请求头
![image](https://github.com/lanqian528/chat2api/assets/58975755/0da0a53b-503b-4f76-92cc-eb71230511c5)
https://github.com/xyhelper/chatgpt-share-server

**Comment by lanqian528** [comment]
v1.1.12 已支持，详情看环境变量AUTH_KEY

**Comment by suidu-pro** [comment]
lq万岁

**Comment by OctHex2016** [comment]
{"detail":"token contains an invalid number of segments"} 是什么情况？
