### ISSUE TITLE
git clone 直接部署的方式  发现 访问ip5005没问题 ip5005/tokens显示 404

### ISSUE THREAD

**Issue by tomridder** [lanqian528/chat2api#63]
git clone 直接部署的方式 
发现 访问ip5005没问题 ip5005/tokens显示 404

**Comment by tomridder** [comment]
> git clone 直接部署的方式 发现 访问ip5005没问题 ip5005/tokens显示 404

2024-05-28 01:21:36,617 | INFO | 5.34.216.89:21718: HEAD /_next/data/_B6xG_cVC4__f_QfOtKz-/api_prefix/tokens.json HTTP/1.1 404 Not Found

logs

**Comment by lanqian528** [comment]
你访问了个啥，你自己看看行么

**Comment by tomridder** [comment]
/api_prefix/tokens 和 /tokes 确实 git clone 方式的都不行 
用docker compose 方式规避了

**Comment by lanqian528** [comment]
> /api_prefix/tokens 和 /tokes 确实 git clone 方式的都不行 用docker compose 方式规避了

这是个什么情况，应该是你部署的时候环境出问题了
