### ISSUE TITLE
请问一下，我使用docker搭建的chat2api，在使用时我查看日志会出现 Model mapping: gpt-3.5-turbo -> text-davinci-002-render-sha

### ISSUE THREAD

**Issue by djhdj1** [lanqian528/chat2api#65]
在使用时我查看日志会出现 Model mapping: gpt-3.5-turbo -> text-davinci-002-render-sha，请问这个正常吗？我该如何直接使用gpt-3.5-turbo?我是非plus用户，在oneapi里使用accesstoken接入的chat2api

**Comment by QAbot-zh** [comment]
正常，官方网页的 3.5 实际上就是指向的 text-davinci-002-render-sha 模型，所以 3.5-turbo\1106\0125 都会重定义到这个模型，和 3.5 api 的能力差异很小

![image](https://github.com/lanqian528/chat2api/assets/40236765/7aba68f1-a1bf-467b-a9ae-732819eb59d2)

**Comment by lanqian528** [comment]
上面那位老哥解释很正确
