### ISSUE TITLE
all模型 画图不出图只有prompt

### ISSUE THREAD

**Issue by suidu-pro** [lanqian528/chat2api#68]
![image](https://github.com/lanqian528/chat2api/assets/58975755/ced18785-7805-4ebc-a777-9aa3f2d8d503)

**Comment by lanqian528** [comment]
我测试画图功能正常

**Comment by suidu-pro** [comment]
经过多次测试，不是每次都不出图，大概率不出就只显示了prompt
由于是请求成功的，日志上也看不出来

**Comment by lanqian528** [comment]
我测了好多次都有呀，奇怪了

**Comment by suidu-pro** [comment]
哈哈那可能是我的问题吧，如果能够稳定复现我再提吧
