### ISSUE TITLE
可否支持下这种图片分析格式

### ISSUE THREAD

**Issue by think007** [lanqian528/chat2api#69]
{
  "stream": true,
  "temperature": 0.8,
  "model": "gpt-4o",
  "messages": [
    {
      "role": "system",
      "content": "中文回答"
    },
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "分析这张图"
        },
        {
          "type": "image_url",
          "image_url": "http://gips3.baidu.com/it/u=1821127123,1149655687&fm=3028&app=3028&f=JPEG&fmt=auto?w=720&h=1280"
        }
      ]
    }
  ]
}

**Comment by lanqian528** [comment]
请问你为什么不能适配一下正确的格式
