### ISSUE TITLE
解决联网搜索后不显示文章链接【7†source】

### ISSUE THREAD

**Issue by wfce** [lanqian528/chat2api#70]
大佬，可以参考下这个项目解决这个问题 https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/internal/chatgpt/request.go
这个项目可以完美显示链接名和URL

似乎代码是：
> 
 			if len(original_response.Message.Metadata.Citations) != 0 {
				r := []rune(original_response.Message.Content.Parts[0].(string))
				offset := 0
				for _, citation := range original_response.Message.Metadata.Citations {
					rl := len(r)
					u, _ := url.Parse(citation.Metadata.URL)
					baseURL := u.Scheme + "://" + u.Host + "/"
					attr := urlAttrMap[baseURL]
					if attr == "" {
						attr = getURLAttribution(secret, deviceId, baseURL)
						if attr != "" {
							urlAttrMap[baseURL] = attr
						}
					}
					u.Fragment = ""
					original_response.Message.Content.Parts[0] = string(r[:citation.StartIx+offset]) + " ([" + attr + "](" + u.String() + " \"" + citation.Metadata.Title + "\"))" + string(r[citation.EndIx+offset:])
					r = []rune(original_response.Message.Content.Parts[0].(string))
					offset += len(r) - rl
				}
			}

![image](https://github.com/lanqian528/chat2api/assets/153601687/ee907c35-6fc8-434b-8348-d5d91cf32ea2)

**Comment by lanqian528** [comment]
很有价值的issue，有时间会加上的

**Comment by lanqian528** [comment]
c06c33ea06364e1daf9c8c0c9752c23f91b88e8d 已支持
