### ISSUE TITLE
【优化】有计划对失效的rt做移除么？

### ISSUE THREAD

**Issue by suidu-pro** [lanqian528/chat2api#72]
例如对出现401报错的rt移除，因为失效的rt增多会大大增加重试次数，导致响应速度变慢
通过人工管理过多的rt也不是件简单的事情，希望有计划能够支持

感谢lq大佬的无私奉献

**Comment by lanqian528** [comment]
需要精细化管理，建议使用oneapi、newapi这种专业的渠道管理程序，那边管理以及很成熟了，我这边再写一遍就没必要了，我这边只是一个简单的聚合，临时使用就行

**Comment by suidu-pro** [comment]
了解 用oneapi就是几千个号，也不太好管理 😂

**Comment by lanqian528** [comment]
> 了解 用oneapi就是几千个号，也不太好管理 😂

其实rt不会过期，如果是普号的话全丢进去不管就行了，多搞点普号就不会封号

**Comment by gkingt** [comment]
> > 了解用oneapi就是几千个号，也不太好管理😂
> 
> 其实rt不会过期，如果是普号的话全丢进去不管就行了，多搞点普号就成为封号

有的账号封号后会导致rt失效，然后就会导致多次重试，而不是rt本身过期，这是不可避免的

**Comment by gkingt** [comment]
不需要什么管理系统 只需要把失效rt重新保存到新的一个txt里，避免误删  然后将失效rt从旧的txt里删除掉，并且清除缓存里的对应rt就可以了,这样可以大程度的方便管理

**Comment by sillyue** [comment]
> 不需要什么管理系统 只需要把失效rt重新保存到新的一个txt里，避免误删 然后将失效rt从旧的txt里删除掉，并且清除缓存里的对应rt就可以了,这样可以大程度的方便管理

请PR

**Comment by gkingt** [comment]
> > 不需要什么管理系统 只需要把失效rt重新保存到新的一个txt里，避免误删 然后将失效rt从旧的txt里删除掉，并且清除缓存里的对应rt就可以了,这样可以大程度的方便管理
> 
> 请PR

我要会的话就pr了 奈何能力有限

**Comment by lanqian528** [comment]
等我有空吧，我会考虑的，最近太忙了

**Comment by lanqian528** [comment]
失效的rt会做移除和显示了
