### ISSUE TITLE
dalle返回信息显示n = 2，但实际上只输出一张图

### ISSUE THREAD

**Issue by cloudsthere** [lanqian528/chat2api#74]
![Snipaste_2024-05-31_17-33-04](https://github.com/lanqian528/chat2api/assets/16861325/8ef8f0c8-20fd-4e2f-af2d-7ff5dcfce5ed)

**Comment by lanqian528** [comment]
我测试了一下，你这样问官网也显示n=2，但实际上也只有一张图。然后真正画两张图的时候是可以正常返回的，因此输出两张图是没有问题的
