### ISSUE TITLE
纯小白,没看懂,如何开启token轮询模式

### ISSUE THREAD

**Issue by jingshaoxiang** [lanqian528/chat2api#75]
services:
  chat2api:
    image: lanqian528/chat2api:latest
    container_name: chat2api
    restart: unless-stopped
    ports:
      - '5005:5005'
    volumes:
      - ./data:/app/data # 挂载一些需要保存的数据
    environment:
      - TZ=Asia/Shanghai # 设置时区
      - ARKOSE_TOKEN_URL=http://arkose:5006/token # 已内置，不要改动
      - AUTHORIZATION="123456"

![image](https://github.com/lanqian528/chat2api/assets/57695499/7fc96a44-f47b-4e68-bac2-b037c2b64a36)

      

 是这样的吗, 这个 123456 是要当成APi key来传入吗,测试了一下不行,求大佬解解疑惑，谢谢!

**Comment by jingshaoxiang** [comment]
![image](https://github.com/lanqian528/chat2api/assets/57695499/7ecf5033-5808-4adc-9af4-f758e416162b)

依旧不可以 TAT

**Comment by lanqian528** [comment]
无法解答，自己不好好看说明

**Comment by jingshaoxiang** [comment]
好久没看邮箱，大佬教训的是，我下次一定好好看说明，那个问题已经解决了，是我的key写的格式不对，谢谢大佬


在 2024年5月31日 ***@***.***> 写道：


Closed #75 as completed.
