### ISSUE TITLE
是否可以支持文件下载 制作一个北京 上海 广州 天津的城市人口饼状图，可以创建一个饼状图出来

### ISSUE THREAD

**Issue by think007** [lanqian528/chat2api#76]
例如 制作一个北京 上海 广州 天津的城市人口饼状图，可以创建一个饼状图出来，或者制作一个北京 上海 广州 天津的城市人口电子表格也可以下载电子表格。官网上有这个功能

**Comment by think007** [comment]
/home/sandbox/.local/lib/python3.11/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 21271 (\N{CJK UNIFIED IDEOGRAPH-5317}) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)
/home/sandbox/.local/lib/python3.11/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 20140 (\N{CJK UNIFIED IDEOGRAPH-4EAC}) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)
/home/sandbox/.local/lib/python3.11/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 12289 (\N{IDEOGRAPHIC COMMA}) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)
/home/sandbox/.local/lib/python3.11/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 19978 (\N{CJK UNIFIED IDEOGRAPH-4E0A}) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)
/home/sandbox/.local/lib/python3.11/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 28023 (\N{CJK UNIFIED IDEOGRAPH-6D77}) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)
/home/sandbox/.local/lib/python3.11/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 24191 (\N{CJK UNIFIED IDEOGRAPH-5E7F}) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)
/home/sandbox/.local/lib/python3.11/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 24030 (\N{CJK UNIFIED IDEOGRAPH-5DDE}) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)
/home/sandbox/.local/lib/python3.11/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 22825 (\N{CJK UNIFIED IDEOGRAPH-5929}) missing from current font.
  fig.canas.print_figure(bytes_io, **kw)
/home/sandbox/.local/lib/python3.11/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 27941 (\N{CJK UNIFIED IDEOGRAPH-6D25}) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)
/home/sandbox/.local/lib/python3.11/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 30340 (\N{CJK UNIFIED IDEOGRAPH-7684}) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)
/home/sandbox/.local/lib/python3.11/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 22478 (\N{CJK UNIFIED IDEOGRAPH-57CE}) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)
/home/sandbox/.local/lib/python3.11/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 24066 (\N{CJK UNIFIED IDEOGRAPH-5E02}) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)
/home/sandbox/.local/lib/python3.11/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 20154 (\N{CJK UNIFIED IDEOGRAPH-4EBA}) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)
/home/sandbox/.local/lib/python3.11/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 21475 (\N{CJK UNIFIED IDEOGRAPH-53E3}) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)
/home/sandbox/.local/lib/python3.11/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 20998 (\N{CJK UNIFIED IDEOGRAPH-5206}) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)
/home/sandbox/.local/lib/python3.11/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 24067 (\N{CJK UNIFIED IDEOGRAPH-5E03}) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)

<<ImageDisplayed>>
饼状图出来上这样的

**Comment by lanqian528** [comment]
会有的

**Comment by think007** [comment]
> 会有的

计划开发吗

**Comment by lanqian528** [comment]
> > 会有的
> 
> 计划开发吗

本来是打算开发的，但是刚刚抓包看了一下，2api的形式是实现不了下载文件的，因此只能放弃了
