### ISSUE TITLE
4o无法识图,后台报错

### ISSUE THREAD

**Issue by KlNon** [lanqian528/chat2api#79]
![image](https://github.com/lanqian528/chat2api/assets/58141387/6dc99cf2-e552-4248-a7e5-cb257301adc3)
具体情况就像这样
后台报错为:
![image](https://github.com/lanqian528/chat2api/assets/58141387/3ada59af-71ae-466a-8846-1c2c373345d9)

**Comment by lanqian528** [comment]
你换个别的图试试，识图我这边测出来是没有问题的。

**Comment by KlNon** [comment]
> 你换个别的图试试，识图我这边测出来是没有问题的。

我知道为什么了,openai抽风,在官网试了试提示无法上传(所有类型的文件都不行)
![image](https://github.com/lanqian528/chat2api/assets/58141387/9032a0eb-ef40-4872-bb80-186bfff1248a)
