### ISSUE TITLE
回复内容重复

### ISSUE THREAD

**Issue by haso2007** [lanqian528/chat2api#84]
请问怎样解决，使用中国本地docker部署加Proxy_URL的方法。
![image](https://github.com/lanqian528/chat2api/assets/30247968/2f0688cc-aec5-4926-9fa9-48b93986bfdd)
![image](https://github.com/lanqian528/chat2api/assets/30247968/ec519942-5f6b-4d75-80b6-915b9ce3ed82)

**Comment by lanqian528** [comment]
版本呢？

**Comment by haso2007** [comment]
![image](https://github.com/lanqian528/chat2api/assets/30247968/dc32330e-678f-45ad-80fa-dfcf42e2485f)
logs:
2024-06-02T09:41:43.246430464Z 2024-06-02 09:41:43,245 | INFO | Model mapping: gpt-4o -> gpt-4o
2024-06-02T09:41:44.758442192Z 2024-06-02 09:41:44,758 | INFO | 172.20.0.1:45706: POST /v1/chat/completions HTTP/1.1 200 OK
感谢大佬

**Comment by haso2007** [comment]
好像回答多时就不会，也不怎么影响使用。
evn设置如下
docker inspect --format '{{ .Config.Env }}' 9285
[POW_DIFFICULTY=00002a PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin LANG=C.UTF-8 GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D PYTHON_VERSION=3.11.9 PYTHON_PIP_VERSION=24.0 PYTHON_SETUPTOOLS_VERSION=65.5.1 PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/dbf0c85f76fb6e1ab42aa672ffca6f0a675d9ee4/public/get-pip.py PYTHON_GET_PIP_SHA256=dfe9fd5c28dc98b5ac17979a953ea550cec37ae1b47a5116007395bfacff2ab9 RETRY_TIMES=5 HISTORY_DISABLED=true PROXY_URL=http://192.168.1.120:5890]

**Comment by haso2007** [comment]
另外还有个问题 /tokens老是打不开，是因为我使用了PROXY_URL 吗。
version: "3"
services:
  chat2api:
    image: lanqian528/chat2api:latest
    container_name: chat2api
    restart: unless-stopped
    ports:
      - 5005:5005
    environment:
      - RETRY_TIMES=5
      - POW_DIFFICULTY=00002a
      - HISTORY_DISABLED=true
      - PROXY_URL=http://192.168.1.120:5890
      - ARKOSE_TOKEN_URL=http://arkose:5006/token
      - AUTHORIZATION=sk123456
    deploy:
      resources:
        limits:
          memory: 1G
  arkose:
    image: lanqian528/funcaptcha_solver:latest
    container_name: funcaptcha_solver
    restart: unless-stopped
    ports:
      - 5006:5006

**Comment by lanqian528** [comment]
> 2024-06-02T11:18:52.604801010Z 2024-06-02 11:18:52,603 | INFO | Chat2Api v1.0.5 | https://github.com/lanqian528/chat2api logs: 2024-06-02T09:41:43.246430464Z 2024-06-02 09:41:43,245 | INFO | Model mapping: gpt-4o -> gpt-4o 2024-06-02T09:41:44.758442192Z 2024-06-02 09:41:44,758 | INFO | 172.20.0.1:45706: POST /v1/chat/completions HTTP/1.1 200 OK 感谢大佬

你版本太老了，是个有问题的版本，现在已经v1.2.0了，你才v1.0.5

**Comment by lanqian528** [comment]
> chat2api:latest

chat2api:v1.2.0 试试

**Comment by haso2007** [comment]
感谢大佬提醒，现在好了。
