### ISSUE TITLE
为什么这种格式无法识图，可否支持这种格式，别的逆向支持

### ISSUE THREAD

**Issue by think007** [lanqian528/chat2api#86]
{
  "max_tokens": 2048,
  "model": "gpt-4o",
  "temperature": 0.2,
  "top_p": 0.5,
  "presence_penalty": 0,
  "frequency_penalty": 0,
  "messages": [
    {
      "role": "system",
      "content": "中文回答"
    },
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "图中内容"
        },
        {
          "type": "image_url",
          "image_url": {
            "url": "https://copyright.bdstatic.com/vcg/creative/cc9c744cf9f7c864889c563cbdeddce6.jpg@h_1280"
          }
        }
      ]
    }
  ],
  "stream": true
}

**Comment by lanqian528** [comment]
本来就支持
