### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by gochendong** [lanqian528/chat2api#88]
http://127.0.0.1:5005/v1/chat/completions

{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "stream": true
   }

response is 500  {
    "detail": "Server error"
}

**Comment by lanqian528** [comment]
现在官网有问题，等等吧

**Comment by gochendong** [comment]
> 现在官网有问题，等等吧

官网上使用没问题
