### ISSUE TITLE
服务器卡死

### ISSUE THREAD

**Issue by code-october** [lanqian528/chat2api#91]
打码服务很吃CPU吗？两度把服务器跑卡死 😂
我把 lanqian528/funcaptcha_solver 放到外部服务器上是不是会好一些

![Clip_2024-06-07_15-55-00](https://github.com/lanqian528/chat2api/assets/148516338/81c27f07-8152-493a-8329-553e5ffed8c8)

**Comment by Yanyutin753** [comment]
什么服务器 阿里云的吗

**Comment by code-october** [comment]
> 什么服务器 阿里云的吗

aws 的 1+1 😂

**Comment by Yanyutin753** [comment]
估计是吧 我azure的1➕1 并发不多可以的

**Comment by lanqian528** [comment]
> 打码服务很吃CPU吗？两度把服务器跑卡死 😂 我把 lanqian528/funcaptcha_solver 放到外部服务器上是不是会好一些
> 
> ![Clip_2024-06-07_15-55-00](https://private-user-images.githubusercontent.com/148516338/337575554-81c27f07-8152-493a-8329-553e5ffed8c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MTE3NjQsIm5iZiI6MTcxNzgxMTQ2NCwicGF0aCI6Ii8xNDg1MTYzMzgvMzM3NTc1NTU0LTgxYzI3ZjA3LTgxNTItNDkzYS04MzI5LTU1M2U1ZmZlZDhjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwMTUxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTU1YWI3N2ZkMTQxY2MyNzQwMTAzMzMxNjlhMjM4Y2RiMjM4YTVhZTI1OGE1NzQzM2RkYTc0OTVkYmY4YTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._cS4ptfdou80yZUIXihyFZr6mKjs63on1UcTLotQXOQ)

不吃cpu，但是chat2api如果你的ip不好就很吃cpu

**Comment by code-october** [comment]
> 不吃cpu，但是chat2api如果你的ip不好就很吃cpu

us-east 的 aws，照理说 IP 应该不差，先观察观察再说

**Comment by code-october** [comment]
> 估计是吧 我azure的1➕1 并发不多可以的

我并发更少了，基本是自用，可能是跟其他服务竞争CPU了
