### ISSUE TITLE
三个账号怎样查看那一个accesstoken过期呢

### ISSUE THREAD

**Issue by haso2007** [lanqian528/chat2api#99]
com.docker.compose.config-hash": "f54d306e028751650c3ba2ff217584c900fcd2d7b89d641d05e33fd445474d57",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "chat2api",
                "com.docker.compose.project.config_files": "docker-compose.yml",
                "com.docker.compose.project.working_dir": "/volume1/docker/chat2api",
                "com.docker.compose.service": "chat2api",
                "com.docker.compose.version": "1.28.5",
                "org.opencontainers.image.created": "2024-06-15T07:32:21.478Z",
                "org.opencontainers.image.description": "A service that can convert ChatGPT on the web to OpenAI API format.",
利用tokens里的查看错误tokens好像没什么用，是我版本太低了吗

**Comment by lanqian528** [comment]
反正会重试，不用管吧

**Comment by lanqian528** [comment]
现在可以显示使用的at了
